services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dropshipping
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"  # Change the host port to 6380
    volumes:
      - redis_data:/data

  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  celery:
    build: ./backend
    command: celery -A main worker --loglevel=info
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  streamlit:
    build: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    volumes:
      - ./frontend:/app

volumes:
  postgres_data:
  redis_data:
